### ISSUE TITLE
GOV.UK keeps randomly changing my email preferences without me asking it to

### ISSUE THREAD

**Issue by Muzer** [alphagov/email-alert-api#1379]
GOV.UK has now twice unilaterally decided to change my email preferences. I set them how I wanted them, stop bloody second-guessing me! And why is it so painful to change them anyway? Surely the "we've changed your email preferences" email should have a link to change them back, rather than a link to where I type my email address, press submit, and then get another email telling me to reset my email preferences.

It's apparently doing this to "make the number of emails you get more manageable.". The number of emails I get is perfectly manageable, at less than one a day. Why is it doing this? I get more emails from this spammy piece of nonsense and then having to get another email to reset my preferences back to how I want them, than I do actual emails with content.

Please reverse this ill-conceived feature.

**Comment by benthorner** [comment]
Hi @Muzer.

I'm sorry to hear you've received an unwanted email and had to change your preferences back. This forum is primarily for developers on GOV.UK to document specific technical issues. In this case, the email you received was a result of the system working as expected. I'm going to close this issue, as there is no technical fault to resolve.

You can provide feedback on any aspect of GOV.UK here: https://www.gov.uk/contact/govuk

**Comment by Muzer** [comment]
You're telling me the system was DESIGNED to randomly change my email preferences, multiple times, when I receive less than one email a day on average?
