### ISSUE TITLE
Unused endpoint to send a single email

### ISSUE THREAD

**Issue by benthorner** [alphagov/email-alert-api#1531]
In 2019 we added an endpoint to send a single email: https://github.com/alphagov/email-alert-api/pull/935.

I suspect the endpoint is unused, and leaving it is just a source of confusion, especially since we have [other means](https://github.com/alphagov/email-alert-api/blob/291f7921bdb012e3a126352120c53d07c49654e5/lib/tasks/bulk_email.rake) to send bespoke email, which seem to be more popular in practice.

**Comment by benthorner** [comment]
@thomasleese @1pretz1 do you know if this endpoint is used anywhere? If it is, we could allude to it in [the API doc](https://github.com/alphagov/email-alert-api/blob/master/docs/api.md#post-emails).

**Comment by 1pretz1** [comment]
Ah, good point @benthorner. I've double checked that the endpoint is unused by searching locally for any uses of the [helper method](https://github.com/alphagov/gds-api-adapters/blob/master/lib/gds_api/email_alert_api.rb#L70-L72) which didn't bring back any relevant results so I think it's safe to delete 👍

**Comment by benthorner** [comment]
Great! Time to say 👋 then:

- https://github.com/alphagov/gds-api-adapters/pull/1020
- https://github.com/alphagov/email-alert-api/pull/1543
