### ISSUE TITLE
Use on other govuk services

### ISSUE THREAD

**Issue by jebw** [alphagov/email-alert-api#1787]
Is it possible to use this service from a `*.service.gov.uk` site which isn't `www.gov.uk` - it looks to be exactly what we need to notifying our users when updates happen to our service (www.trade-tariff.service.gov.uk)?

Thanks in advance

**Comment by KludgeKML** [comment]
Hey @jebw - it's tied quite heavily to page alerts on GOV.UK itself at the moment rather than service pages, so it might not be appropriate for your need. Have you taken a look at https://www.notifications.service.gov.uk/ (GOV.UK Notify)? That might provide what you're looking for.

**Comment by jebw** [comment]
Hey, we were hoping to avoid holding the email addresses (PII) but sounds this isn't the right option. Thanks for the reply anyway.
