### ISSUE TITLE
Handle tags being provided in different orderings or with duplicated values

### ISSUE THREAD

**Issue by rboulton** [alphagov/email-alert-api#35]
So that the ordering of tag values doesn't matter (in either subscription or notification APIs), we should:

 - validate (in the model) that the values of tags stored associated with each tag type are sorted and uniqued.
 - sort and uniq the tag values in the controllers.

**Comment by tijmenb** [comment]
Closing this as I think this is no longer an issue. The ordering of the links are not guaranteed anymore, and this has not had an effect on the email-alert-api. In any case, if this were a problem it would have appeared on our backlog.
